version: "3.8"

services:
    ros_dev:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                USERNAME: bumrc
                USER_UID: 1000
                USER_GID: 1000
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all # alternatively, use `count: all` for all GPUs
                          capabilities: [gpu]
        image: ros_humble
        container_name: ros_humble_dev

        stdin_open: true # Equivalent to -i
        tty: true # Equivalent to -t

        user: "1000:1000"
        network_mode: "host" # Equivalent to --network=host
        ipc: "host" # Equivalent to --ipc=host

        privileged: true

        volumes:
            - ./ros_ws:/ros_ws

        # Optional: For display / gui applications
        # environment:
        #   - DISPLAY=${DISPLAY}
        #   - QT_X11_NO_MITSHM=1
